version: '3.8'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1111
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/PhotoSnap
    ports:
      - "8000:8000"
