version: '3.8'

services:
  db:
    image: mysql
    environment:
<<<<<<< HEAD
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWORD}
=======
      - MYSQL_ROOT_PASSWORD={DB_USER_PASSWORD}
    volumes:
      - /var/lib/mysql
>>>>>>> origin/bugFix
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/PhotoSnap
    ports:
      - "8000:8000"
    env_file:
      - .env
